### PR TITLE
Add some more convenient assert macros and unit test

### PR DESCRIPTION
**Pull request by uschwes**

### CODE REVIEW

**Comment by uschwes** [comment]
retest this please

**Comment by uschwes** [comment]
@HannesSommer good to merge? (sorry, but currently you're the final instance ☺)

**Comment by HannesSommer** [comment]
lgtm. :+1:  for adding assertions unit tests!
Tip: You could have build tests for the effect of _DBG independent of an external NDEBUG macro: have two cpp files, one unsets NDEBUG at the head and the other sets it, each before including the assert macros.

**Comment by uschwes** [comment]
Good idea. Does this work in a single cpp file too?  One could wrap a second test in a #define / #undef section then.

**Comment by HannesSommer** [comment]
Ah, no, that won't work, because you would need to reinclude, but the guards and many other things are against that. (The assert macros do not evaluate NDEBUG, the get defined differently depending on NDEBUG)

**Comment by HannesSommer** [comment]
retest this please

**Comment by uschwes** [comment]
retest this please

**Pull request merged**
