### PR TITLE
Removed stream output for ptr types

### PR DESCRIPTION
**Pull request by uschwes**
E.g. stream operator for std::unique_ptr is not defined

### CODE REVIEW

**Comment by uschwes** [comment]
Retest this please

**Comment by uschwes** [comment]
@HannesSommer 
Hmm, not hooked up to Jenkins any more?

**Comment by HannesSommer** [comment]
Why not have the value in there? But I don't mind.

**Comment by uschwes** [comment]
Because the pointer is null. Outputting it is not that useful.

**Comment by HannesSommer** [comment]
Ah,oops :). Yes, agreed. Somehow i was in the assert_null case. Lgtm then.

**Comment by uschwes** [comment]
OK this should be trivial enough without jenkins

**Pull request merged**
