### PR TITLE
Protect the static random number generator used for creating ids.

### PR DESCRIPTION
**Pull request by schneith**
Resolves https://github.com/ethz-asl/multiagent_mapping/issues/1663
@furgalep

### CODE REVIEW

**Comment by simonlynen** [comment]
Lgtm

**Comment by simonlynen** [comment]
add to whitelist

**Comment by schneith** [comment]
@simonlynen @furgalep 
please merge if you agree, i don't have push access.

**Comment by schneith** [comment]
Oh, the intialization of a static variable might actually not be threadsafe before c++11. Will fix.

**Comment by simonlynen** [comment]
@schneith this is fine since you won't have unique_lock pre c++11 anyway so this has to be compiled with c++11.

**Pull request merged**
